import { createFromRoot } from "codama";
import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  statSync,
  existsSync,
} from "node:fs";
import path from "node:path";
import { parse, Lang } from "@ast-grep/napi";

const PROGRAM_ID = "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr";

const idlPath = path.join(process.cwd(), "src", "idl", "farms.json");
const anchorIdl = JSON.parse(readFileSync(idlPath, "utf-8"));

const codama = createFromRoot(rootNodeFromAnchor(anchorIdl));

const outputDir = path.join(process.cwd(), "src", "@codegen", "farms");

// renderVisitor first arg is the "package folder"
// generatedFolder="" puts files directly in the output dir
await codama.accept(
  renderVisitor(outputDir, {
    formatCode: true,
    deleteFolderBeforeRendering: true,
    syncPackageJson: false,
    generatedFolder: "",
  })
);

console.log("TypeScript client generated!");

// --- Post-processing ---
fixEmptyProgramAddresses(outputDir, PROGRAM_ID);
stripErrorProdGuards(outputDir);

console.log("All post-processing complete.");

// --- Shared helpers ---

/** Parse a TS file, return { root, source } */
function parseTS(filePath) {
  const source = readFileSync(filePath, "utf-8");
  const ast = parse(Lang.TypeScript, source);
  return { root: ast.root(), source };
}

/** Re-parse source text after edits */
function reparse(source) {
  const ast = parse(Lang.TypeScript, source);
  return ast.root();
}

/** Remove trailing whitespace on lines, collapse 3+ newlines, strip blank lines after { and before } */
function cleanupWhitespace(source) {
  return source
    .replace(/^[ \t]+$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/\{\n\n/g, "{\n")
    .replace(/\n\n(\s*\})/g, "\n$1");
}

/** Walk a directory recursively, calling fn(filePath) for each .ts file */
function walkTS(dir, fn) {
  for (const entry of readdirSync(dir)) {
    const fullPath = path.join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      walkTS(fullPath, fn);
    } else if (entry.endsWith(".ts")) {
      fn(fullPath);
    }
  }
}

// --- Post-processing passes ---

/**
 * Fix empty program addresses generated by Anchor v0 IDLs.
 * Replaces `'' as Address<''>` with the actual program ID using AST matching.
 */
function fixEmptyProgramAddresses(dstDir, programId) {
  walkTS(dstDir, (filePath) => {
    const { root } = parseTS(filePath);

    // Try both single and double quote patterns (depends on formatCode setting)
    const emptyAddrs = [
      ...root.findAll({
        rule: { kind: "as_expression", pattern: "'' as Address<''>" },
      }),
      ...root.findAll({
        rule: { kind: "as_expression", pattern: '\"\" as Address<\"\">' },
      }),
    ];

    if (emptyAddrs.length === 0) return;

    const edits = emptyAddrs.map((node) =>
      node.replace(`"${programId}" as Address<"${programId}">`)
    );
    writeFileSync(filePath, root.commitEdits(edits));
    console.log(`  -> Fixed empty program addresses: ${filePath}`);
  });
}

/**
 * Strip `process.env.NODE_ENV !== 'production'` guards from error files
 * so error messages are always available (even in production builds).
 *
 * All passes use @ast-grep/napi for structural AST matching.
 */
function stripErrorProdGuards(dstDir) {
  const errorsDir = path.join(dstDir, "errors");
  if (!existsSync(errorsDir)) return;

  for (const file of readdirSync(errorsDir).filter(
    (f) => f.endsWith(".ts") && f !== "index.ts"
  )) {
    const filePath = path.join(errorsDir, file);
    let source = readFileSync(filePath, "utf-8");

    // --- Pass 1: Unwrap all `if (process.env.NODE_ENV !== 'production') { ... }` blocks ---
    let root = reparse(source);
    const ifNodes = root.findAll({
      rule: {
        kind: "if_statement",
        has: {
          kind: "parenthesized_expression",
          has: {
            kind: "binary_expression",
            pattern: 'process.env.NODE_ENV !== "production"',
          },
        },
      },
    });

    if (ifNodes.length === 0) continue; // not an error file with prod guards

    let edits = ifNodes.map((node) => {
      const block = node.field("consequence");
      // Extract statements inside { }, stripping the braces
      const inner = block.text().slice(1, -1);
      return node.replace(inner);
    });
    source = root.commitEdits(edits);

    // --- Pass 2: Remove the dead fallback return statement ---
    root = reparse(source);
    const fallbackReturns = [
      ...root.findAll(
        "return 'Error message not available in production bundles.'"
      ),
      ...root.findAll(
        'return "Error message not available in production bundles."'
      ),
    ];
    if (fallbackReturns.length > 0) {
      edits = fallbackReturns.map((node) => {
        const stmt =
          node.kind() === "return_statement" ? node : node.parent();
        return stmt.replace("");
      });
      source = root.commitEdits(edits);
    }

    // --- Pass 3: Remove `(xxxErrorMessages as Record<...>)` casts ---
    root = reparse(source);
    const casts = root.findAll({
      rule: {
        kind: "parenthesized_expression",
        has: {
          kind: "as_expression",
          has: {
            kind: "identifier",
            regex: "ErrorMessages$",
          },
        },
      },
    });
    if (casts.length > 0) {
      edits = casts.map((node) => {
        const asExpr = node.find({ rule: { kind: "as_expression" } });
        const ident = asExpr.children()[0];
        return node.replace(ident.text());
      });
      source = root.commitEdits(edits);
    }

    // --- Pass 4: Strip `| undefined` from the error messages type annotation ---
    root = reparse(source);
    const unionTypes = root.findAll({
      rule: {
        kind: "union_type",
        has: { kind: "literal_type", regex: "undefined" },
      },
    });
    edits = [];
    for (const node of unionTypes) {
      // Verify this union_type belongs to an ErrorMessages declaration
      let ancestor = node.parent();
      let isErrorMessages = false;
      while (ancestor) {
        if (ancestor.kind() === "variable_declarator") {
          const name = ancestor.field("name");
          if (name && /ErrorMessages$/.test(name.text())) {
            isErrorMessages = true;
          }
          break;
        }
        ancestor = ancestor.parent();
      }
      if (!isErrorMessages) continue;

      // Keep just the real type (not '|' or 'undefined')
      const realType = node
        .children()
        .find((c) => c.kind() !== "|" && c.text() !== "undefined");
      edits.push(node.replace(realType.text()));
    }
    if (edits.length > 0) {
      source = root.commitEdits(edits);
    }

    // --- Pass 5: Merge `let X: T; X = {...};` into `const X: T = {...};` ---
    root = reparse(source);
    const letDecls = root.findAll({
      rule: {
        kind: "lexical_declaration",
        has: {
          kind: "variable_declarator",
          has: {
            kind: "identifier",
            regex: "ErrorMessages$",
          },
        },
      },
    });

    for (const letDecl of letDecls) {
      const declarator = letDecl.find({
        rule: { kind: "variable_declarator" },
      });
      const varName = declarator.field("name").text();
      const typeAnnot = declarator.find({
        rule: { kind: "type_annotation" },
      });
      if (!typeAnnot) continue;

      // Find the following assignment statement for this variable
      const assignStmts = root.findAll({
        rule: {
          kind: "expression_statement",
          has: {
            kind: "assignment_expression",
          },
        },
      });

      const assignStmt = assignStmts.find((stmt) => {
        const assignExpr = stmt.find({
          rule: { kind: "assignment_expression" },
        });
        if (!assignExpr) return false;
        const left = assignExpr.field("left");
        return left && left.text() === varName;
      });
      if (!assignStmt) continue;

      const assignExpr = assignStmt.find({
        rule: { kind: "assignment_expression" },
      });
      const rhs = assignExpr.field("right");

      const merged = `const ${varName}${typeAnnot.text()} = ${rhs.text()};`;
      edits = [letDecl.replace(merged), assignStmt.replace("")];
      source = root.commitEdits(edits);
      root = reparse(source); // re-parse for next iteration
    }

    source = cleanupWhitespace(source);

    writeFileSync(filePath, source);
    console.log(`  -> Stripped prod guards: ${filePath}`);
  }
}
